// Note : if a ^ is used in the script it is then a 1-second pause of the transcript reading.

let transcripts = {
    "Intro" : "^^^^In Toxic Rōnin, you play as Miyamoto Musashi, a Japanese warrior who aspires to become the greatest swordsman alive. In a bout to gain prestige on his path to glory, Musashi kills two combatants of the distinguished Yoshioka School, singlehandedly disgracing their reputation. Now the warriors seek revenge against the wandering samurai who dared to dishonour them... ^^^^^^ The poison is spreading. I’m dripping with sweat, I feel lightheaded, there’s a stabbing in my stomach like I swallowed a pair of sai. I thought I could trust my hosts, but they were obviously loyal to the Yoshioka School. So much for the right of hospitality. We all ate from the same pot, so there must be an antidote. I need to get to their school... before it’s too late.",
    "forestIntro" : "^^^The entrance to the Yoshioka School is beyond the cave at the edge of these woods. Somehow I’ve got to get past their sentries. I did it once before, but with the state I’m in now I need to be more vigilant than ever. I can’t control the shaking of my limbs. Can’t even hold my katana still. This is going to be tough, but I’ve no choice if I want to see the sun rise tomorrow. Musashi stopped in his tracks. Though his usually acute senses were dulled somewhat, no poison could numb his instincts. Danger lay in the near vicinity to his left. The question was, did he have the strength to confront it, or should he take the risk of traversing the treacherous cliff on his right instead?",
    "riddleIntro" : "The unassuming wall that loomed before him seemed just another mountain face in a museum of rock, but Musashi knew its secrets. This wasn’t a wall, but an entrance. The cave into the school is here, I remember it! Only problem is, they change the unlock sequence to ensure only authorised members can enter. I just need to find the new way in.",
    "ahRiddle" : "Ah, a riddle.",
    "notHere" : "Hmm. Not here.",
    "riddle" : "I’m often seen but sometimes hidden, guarding spaces, unbidden. What am I?",
    "openDoor" : "The spoken password caused a rectangular section of the rock to recede into the wall, revealing a doorway into the Yoshiokah school. Musashi had reached his destination. Just one challenge remained.",
    "finale" : "Musashi strode the empty halls of the Yoshiokah school throwing caution to the wind. He was running out of time. I can feel my constitution draining by the minute. I’m… losing control… of my breathing….my limbs think twice before obeying… so… cold. I need to end this… fast! By the will of Shinigami, you should have been taken from this world hours ago. Is it a ghost I see before me? It will take a lot more than… a simple poison… to stop Miyamoto Musashi from achieving his goal. Not much more, it seems! You can’t even string a sentence together without needing to catch your breath! Musashi had had enough talking. This would only end one way. He had no second thoughts as he slid his katana from its sheath.",
    "ending" : "Musashi didn’t even take a moment to regard the corpse that lay at his feet, the life he’d just taken. He simply reached down, searched the body’s pockets and pulled out a glass vile. This is it. My hosts each had this interesting little drink with them the night we ate together. A small bottle with a cork in the shape of a sakura flower. ‘Helps with digestion,’ they said. They were right! The story of the samurai who battled with death herself and still managed to vanquish his enemies became legend. Generations of young swordsmen modelled their lives and aspirations after the example set by Miyamoto Musashi, the Toxic Ronin. ^^^^",
    "forestObstacle" : "Reaching the edge of the forest, the trees suddenly gave way to a thin stone pathway littered with stones from the mountain face on the left side of the alley. On the right was nothing but a drop into the unforgiving waves. The shivering samurai would need to fight the effects of the toxin and find his balance and control. After examining the wall of rock on his left, Musashi noticed something was wrong. I knew it couldn’t be as easy as it seemed. There are unnatural ridges in the rock wall. I suspect they’ve planted traps to push unwanted visitors into the ocean. I must think carefully before each step. Looks like I need to stay low for three steps, jump for the next, crouch again, then jump over the last one.",
    "forestFight" : "Musashi moved with nonchalance and confidence, but he took caution in every step. He knew his best approach was to act unaware. Give his opponent or opponents the feeling that they had the advantage. Poison or no, the samurai’s unwavering discipline and determination made him a danger in any fight. His enemies would find out the hard way that assuming victory against Miyamoto Musashi was a sure way to sink yourself into an early grave."

}

export default transcripts